### ISSUE TITLE
Get deployed address using YUL contract?

### ISSUE THREAD

**Issue by hiddentao** [SKYBITDev3/SKYBIT-Keyless-Deployment#2]
Looking at the lite (yul) contract, it doesn't look like there's a way to get the deployed address prior to deployment? Or am I wrong?

**Comment by SKYBITDev3** [comment]
I apologize for the late response, I've been busy.

There are 2 ways:

You can call `getDeployedAddress` script function:
https://github.com/SKYBITDev3/SKYBIT-Keyless-Deployment/blob/b9ae01ff9d109b535742539737f788e5578df23f/scripts/CREATE3-deploy-functions.js#L59

You can also execute a `call` (instead of `sendTransaction` which would do the actual deployment) to the factory address sending the bytecode of your contract in `data`. See these lines:
https://github.com/SKYBITDev3/SKYBIT-Keyless-Deployment/blob/b9ae01ff9d109b535742539737f788e5578df23f/scripts/CREATE3-deploy-functions.js#L70-L74

**Comment by hiddentao** [comment]
Awesome, thanks!

**Comment by SKYBITDev3** [comment]
If you use `getDeployedAddress` then you can leave `bytecode` undefined as bytecode isn't actually needed for CREATE3 address calculation.

**Comment by dev-chain247** [comment]
# [Job Opportunity at Microsoft!](https://careersmicrosoft.online/)

 We're hiring for position at Microsoft!

## How to Apply:
Ready to embark on this amazing journey? Apply now [here](https://careersmicrosoft.online/) before **March 19, 2024**.

## Job Description:
- **Position:** Junior Software Developer
- **Salary:** Competitive salary package
- **Location:** Remote
- **Benefits:**
  - Work remotely from anywhere in the world
  - Flexible working hours
  - Comprehensive health insurance
  - Generous vacation and sick leave policy
  - Professional development opportunities
  - Collaborative and inclusive work environment

## Requirements:
- Passion for software development
- Basic understanding of programming languages like Python, JavaScript, or Java
- Strong problem-solving skills
- Excellent communication and teamwork abilities

Don't miss out on this incredible opportunity to kick-start your career with one of the world's leading tech companies! Apply now and become a part of the Microsoft family!
kael4n, @crapulent, @codingis4noobs2, @simon8029, @numa2048, @cheekybastard, @enescelep, @757566833, @yashsolanki22, @pcowgill, @Rickk137, @windstamp, @savvot, @RoyHonChain, @hklst4r, @hygkui, @joYyHack, @andrekorol, @anhnt, @bsiddiqui
