### ISSUE TITLE
ProviderError: only replay-protected (EIP-155) transactions allowed over RPC

### ISSUE THREAD

**Issue by sdn222** [SKYBITDev3/SKYBIT-Keyless-Deployment#3]
I was trying to keylessly deploy the factory contract to polygonMumbai testnet but I am getting the following error:
![image](https://github.com/SKYBITDev3/SKYBIT-Keyless-Deployment/assets/114336669/7a31efa7-f37a-4e97-b2cf-2ed91ba593f7)

Getting the same error with baseSepolia as well

**Comment by SKYBITDev3** [comment]
Many nodes these days enforce EIP-155 (so don't allow chain ID to be 0). I discussed that issue at https://github.com/SKYBITDev3/SKYBIT-Keyless-Deployment#replay-protection. Please try different nodes, including paid node servers that enable `--rpc.allow-unprotected-txs`.

**Comment by sdn222** [comment]
I see. Didn't notice it was already discussed. Thanks for the reply.

**Comment by zajck** [comment]
Hi, @SKYBITDev3 although your suggestion works, it can be tricky in practice to execute it. For example, I tried to find unprotected polygonMumbai node, but all of them are protected. And to run my own node, where I could enable unprotected tx, I would have to become a validator, which is again unpractical (it would take some time to be accepted, and I have no intention to be a validator).

May I propose another approach in addition to the existing keyless approach. 
Most of the chains (including those that generally do not support pre EIP-155 transactions) have the `0x4e59b44847b379578588920ca78fbf26c0b4956c` deployed (https://github.com/Arachnid/deterministic-deployment-proxy).
Due to its popularity, some even include it in their genesis block.

It has some flaws, but it's still good enough to be used to deploy your contract since front-running should not be a problem in this case. A possible implementation:

https://github.com/zajck/SKYBIT-Keyless-Deployment/blob/2c0b2939611e29584c9619313dddf3d2ecebee53/scripts/deployKeylessly-Create3Factory.js#L20-L29

In this case, `SKYBITLite` gets the address `0xA41B0E32C8F1E0F20fe57bFFe64c32fDF5A03AD1`. So far I have deployed it on polygonMumbai, polgonAmoy and sepolia.

If you want to include this option, it might help somebody else on other chains.

**Comment by SKYBITDev3** [comment]
> I tried to find unprotected polygonMumbai node, but all of them are protected.

There are some paid node services that enable `--rpc.allow-unprotected-txs` in their geth instances, e.g. I think GetBlock and AllThatNode, and aren't very expensive e.g. 50 USD, so I think that option should be explored.

 
> Most of the chains (including those that generally do not support pre EIP-155 transactions) have the `0x4e59b44847b379578588920ca78fbf26c0b4956c` deployed (https://github.com/Arachnid/deterministic-deployment-proxy). Due to its popularity, some even include it in their genesis block.
> 
> It has some flaws, but it's still good enough to be used to deploy your contract since front-running should not be a problem in this case.

I ran a test on 230 blockchains recently and found that Arachnid's factory contract exists on 156, which is around two-thirds.

In future a new blockchain onto which you want to deploy your contract may not have Arachnid's factory contract, so in order for your contract to get the same address as on other blockchains, you'd then have to first deploy Arachnid's factory contract keylessly (if allowed) before you can use it to deploy SKYBITLite and then use SKYBITLite to deploy your contract.

Your proposal of using Arachnid's factory contract to deploy SKYBITLite is certainly an option, one that some may choose to take after weighing the many pros and cons.


> A possible implementation:
> 
> https://github.com/zajck/SKYBIT-Keyless-Deployment/blob/2c0b2939611e29584c9619313dddf3d2ecebee53/scripts/deployKeylessly-Create3Factory.js#L20-L29
> 
> In this case, `SKYBITLite` gets the address `0xA41B0E32C8F1E0F20fe57bFFe64c32fDF5A03AD1`. So far I have deployed it on polygonMumbai, polgonAmoy and sepolia.

I think it'd be better to set salt to 0, assuming that the intention is to have your deployed SKYBITLite factory be a public good for use by anyone.

**Comment by SKYBITDev3** [comment]
I've added the script https://github.com/SKYBITDev3/SKYBIT-Keyless-Deployment/blob/main/scripts/deployViaDDP-Create3Factory.js which uses Arachnid's factory to deploy a chosen CREATE3 factory, for those who want to try such an option.
